export const AI_SUMMARY_ADD_ENTRY = 'AI_SUMMARY_ADD_ENTRY';

export const AI_SUMMARY_SET_STATUS = 'AI_SUMMARY_SET_STATUS';

export const AI_SUMMARY_SET_RESULT = 'AI_SUMMARY_SET_RESULT';

export const AI_SUMMARY_RESET = 'AI_SUMMARY_RESET';

export const AI_SUMMARY_TOGGLE_PANEL = 'AI_SUMMARY_TOGGLE_PANEL';

export const AI_SUMMARY_SET_ERROR = 'AI_SUMMARY_SET_ERROR';

export const AI_SUMMARY_UPDATE_PARTICIPANT = 'AI_SUMMARY_UPDATE_PARTICIPANT';
