<script lang="ts">
	import { Alert, Button, Spinner, icons } from '@facile/muse';
	import { ApiError, generateCallSummary, type CallId, type CallSummary } from '$lib/api';
	import { formatDateTime } from '$lib/format';

	interface Props {
		callId: CallId;
		summary?: CallSummary;
		hasTranscript: boolean;
	}

	let { callId, summary, hasTranscript }: Props = $props();

	let generated = $state<CallSummary | undefined>(undefined);
	let pending = $state(false);

	const current = $derived(generated ?? summary);

	let error = $state('');

	function messageFor(e: unknown): string {
		if (e instanceof ApiError && e.status === 503) {
			return 'AI summaries are not configured on this server (no Anthropic key).';
		}
		if (e instanceof ApiError && e.status === 409) {
			return 'This call has no transcript, so there is nothing to summarise.';
		}
		if (e instanceof ApiError && e.status === 403) {
			return 'Only the room owner can generate a summary.';
		}
		return e instanceof Error ? e.message : String(e);
	}

	async function generate() {
		pending = true;
		error = '';
		try {
			generated = await generateCallSummary(callId);
		} catch (e) {
			error = messageFor(e);
		} finally {
			pending = false;
		}
	}
</script>

<div class="flex flex-col gap-4">
	{#if error}
		<Alert tone="danger" title="Summary unavailable">{error}</Alert>
	{/if}

	{#if pending}
		<div class="flex items-center gap-4">
			<Spinner />
			<p class="text-fc-sm text-fc-fg-muted">
				Generating the summary. This can take up to two minutes.
			</p>
		</div>
	{:else if current}
		<p class="text-fc-sm whitespace-pre-wrap text-fc-fg">{current.content}</p>
		<p class="text-fc-xs text-fc-fg-muted">
			Generated by {current.model} on {formatDateTime(current.created_at)}
		</p>
	{:else if !hasTranscript}
		<p class="text-fc-sm text-fc-fg-muted">
			A summary needs a transcript. Turn transcription on during the call to get one.
		</p>
	{:else}
		<p class="text-fc-sm text-fc-fg-muted">No summary has been generated for this call yet.</p>
	{/if}

	{#if hasTranscript}
		<div>
			<Button
				variant={current ? 'outline' : 'primary'}
				size="sm"
				icon={current ? icons.refresh : icons.bolt}
				disabled={pending}
				onclick={generate}
			>
				{current ? 'Regenerate summary' : 'Generate summary'}
			</Button>
		</div>
	{/if}
</div>
